const FLAGS: Record<string, string> = {
  // AFC (Asia)
  "Australia": "🇦🇺",
  "Bahrain": "🇧🇭",
  "China": "🇨🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "North Korea": "🇰🇵",
  "Oman": "🇴🇲",
  "Qatar": "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  "South Korea": "🇰🇷",
  "Syria": "🇸🇾",
  "United Arab Emirates": "🇦🇪",
  "Uzbekistan": "🇺🇿",

  // CAF (Africa)
  "Algeria": "🇩🇿",
  "Cape Verde": "🇨🇻",
  "Ghana": "🇬🇭",
  "Cameroon": "🇨🇲",
  "DR Congo": "🇨🇩",
  "Egypt": "🇪🇬",
  "Ivory Coast": "🇨🇮",
  "Mali": "🇲🇱",
  "Morocco": "🇲🇦",
  "Nigeria": "🇳🇬",
  "Senegal": "🇸🇳",
  "South Africa": "🇿🇦",
  "Tunisia": "🇹🇳",
  "Zambia": "🇿🇲",

  // CONCACAF
  "Canada": "🇨🇦",
  "Curaçao": "🇨🇼",
  "Costa Rica": "🇨🇷",
  "Haiti": "🇭🇹",
  "Honduras": "🇭🇳",
  "Jamaica": "🇯🇲",
  "Mexico": "🇲🇽",
  "Panama": "🇵🇦",
  "Trinidad and Tobago": "🇹🇹",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "USMNT": "🇺🇸",

  // CONMEBOL (South America)
  "Argentina": "🇦🇷",
  "Bolivia": "🇧🇴",
  "Brazil": "🇧🇷",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Ecuador": "🇪🇨",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Uruguay": "🇺🇾",
  "Venezuela": "🇻🇪",

  // OFC (Oceania)
  "New Zealand": "🇳🇿",

  // UEFA (Europe)
  "Albania": "🇦🇱",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Bosnia and Herzegovina": "🇧🇦",
  "Bosnia": "🇧🇦",
  "Bosnia & Herzegovina": "🇧🇦",
  "Croatia": "🇭🇷",
  "Czech Republic": "🇨🇿",
  "Czechia": "🇨🇿",
  "Denmark": "🇩🇰",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Greece": "🇬🇷",
  "Hungary": "🇭🇺",
  "Iceland": "🇮🇸",
  "Ireland": "🇮🇪",
  "Italy": "🇮🇹",
  "Netherlands": "🇳🇱",
  "North Macedonia": "🇲🇰",
  "Norway": "🇳🇴",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Serbia": "🇷🇸",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Spain": "🇪🇸",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Turkey": "🇹🇷",
  "Ukraine": "🇺🇦",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
}

export function getFlag(teamName: string): string {
  return FLAGS[teamName] ?? "🏳️"
}
